defaults:  
  - _self_  
  - override hydra/hydra_logging: none  
  - override hydra/job_logging: none  



batch_size: 4
learning_rate: 0.001
num_epochs: 30
dataset: MNIST
save_path: '/home/christian/Desktop/XYLab/Compression-project/model/'
save_dir: '/home/christian/Desktop/XYLab/Compression-project/recompressed/'
train: True