defaults:  
  - _self_  
  - override hydra/hydra_logging: none  
  - override hydra/job_logging: none  



batch_size: 4
learning_rate: 2.5e-4
num_epochs: 30
dataset: MNIST
save_path: './save_images/'
train: True